export default [
    {
        index: 1,
        name: "Code Warriors",
        event: "TechFest 2024 Hackathon",
        description: "looking for passionate to build an AI platform",
        teamSize: "4",
        spotsLeft: "2",
        skillsNeeded: ["React js", "Node.Js", "AI/ML"],
        leader: "Arjay Patel",
    },
    {
        index: 2,
        name: "Innovation Squad",
        event: "Hackathon",
        description: "looking for passionate to build an AI platform",
        teamSize: "3",
        spotsLeft: "1",
        skillsNeeded: ["React", "Node.Js"],
        leader: "Akshat Pareek",
    },
    {
        index: 3,
        name: "Warrirors of Nitp",
        event: "Football",
        description: "looking for passionate to build an AI platform",
        teamSize: "10",
        spotsLeft: "4",
        skillsNeeded: ["frontman", "middleman", "goalkeeper", "refree"],
        leader: "Kartikey Gangwar",
    },
    {
        index: 4,
        name: "Technika",
        event: "technologia",
        description: "looking for passionate to build an AI platform",
        teamSize: "4",
        spotsLeft: "1",
        skillsNeeded: ["Frontend", "backend", "Data Management"],
        leader: "Kartikey",
    },
    {
        index: 5,
        name: "Dirichlet",
        event: "Technika",
        description: "looking for passionate to build an AI platform",
        teamSize: "5",
        spotsLeft: "0",
        skillsNeeded: ["UI designner", "AI /ML", "IoT"],
        leader: "Shivam Bhai",
    }
]